# -*- coding: utf-8 -*-
"""Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RwehV4inQpnc8l0zD-_XVbe4WeEYRBv
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import google.generativeai as genai
import os

# ==========================================
# 1. Configuration & Setup
# ==========================================
st.set_page_config(page_title="ESG Finance Bot", layout="wide", page_icon="📈")

# Safely check Streamlit Secrets, then environment variables
if "GEMINI_API_KEY" in st.secrets:
    API_KEY = st.secrets["GEMINI_API_KEY"]
else:
    API_KEY = os.environ.get("GEMINI_API_KEY")

# Configure the AI model if the key exists
if API_KEY:
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
else:
    model = None
    st.error("⚠️ API Key not found! Please check your Streamlit Cloud Secrets.")

# ==========================================
# 2. Data & System Prompt
# ==========================================
ESG_DATA = [
    {"name":"TCS", "sector":"IT", "e":72, "s":78, "g":81, "esg":77, "roe":47.5, "roa":24.2, "pe":28.5},
    {"name":"Infosys", "sector":"IT", "e":75, "s":76, "g":79, "esg":77, "roe":31.8, "roa":18.5, "pe":25.2},
    {"name":"Wipro", "sector":"IT", "e":71, "s":74, "g":77, "esg":74, "roe":17.2, "roa":11.1, "pe":22.1},
    {"name":"HDFC Bank", "sector":"Banking", "e":52, "s":65, "g":82, "esg":66, "roe":16.5, "roa":1.9, "pe":19.8},
    {"name":"ICICI Bank", "sector":"Banking", "e":48, "s":62, "g":78, "esg":63, "roe":15.2, "roa":1.7, "pe":17.5},
    {"name":"Reliance", "sector":"Energy", "e":45, "s":58, "g":72, "esg":58, "roe":10.8, "roa":5.2, "pe":24.6},
    {"name":"ITC", "sector":"FMCG", "e":62, "s":71, "g":76, "esg":70, "roe":27.5, "roa":15.8, "pe":22.4},
    {"name":"Asian Paints", "sector":"Materials", "e":61, "s":68, "g":74, "esg":68, "roe":35.2, "roa":20.1, "pe":48.5},
    {"name":"Maruti Suzuki", "sector":"Auto", "e":55, "s":63, "g":71, "esg":63, "roe":15.8, "roa":9.8, "pe":26.8},
    {"name":"Tata Steel", "sector":"Metals", "e":42, "s":55, "g":65, "esg":54, "roe":22.5, "roa":5.8, "pe":8.2},
    {"name":"NTPC", "sector":"Utilities", "e":38, "s":60, "g":68, "esg":55, "roe":12.8, "roa":3.2, "pe":9.8},
    {"name":"Sun Pharma", "sector":"Pharma", "e":65, "s":70, "g":72, "esg":69, "roe":14.5, "roa":10.2, "pe":32.5},
    {"name":"HUL", "sector":"FMCG", "e":68, "s":75, "g":80, "esg":74, "roe":85.2, "roa":18.5, "pe":55.2},
    {"name":"Bajaj Finance", "sector":"NBFC", "e":45, "s":60, "g":75, "esg":60, "roe":22.8, "roa":4.8, "pe":28.5},
    {"name":"L&T", "sector":"Industrial", "e":50, "s":65, "g":73, "esg":63, "roe":14.2, "roa":4.5, "pe":22.8},
]

df = pd.DataFrame(ESG_DATA)

SYSTEM_PROMPT = f"""
You are ESGAnalyst, an expert AI assistant specializing in ESG scoring and its correlation with financial performance of Indian listed firms. You are helping an MBA student at MSRUAS with their dissertation.
Here is the data context you have access to: {df.to_json(orient='records')}

Context: India-specific — SEBI BRSR framework, NSE/BSE listed firms, Nifty 100 universe.
Be concise (3-5 sentences), data-driven, cite specific firms when relevant, and connect ESG to financial implications. Respond as if advising an MBA dissertation student.
"""

# ==========================================
# 3. Main Dashboard UI (Left Column)
# ==========================================
col1, col2 = st.columns([1.5, 1], gap="large")

with col1:
    st.title("📊 ESG Finance Dashboard")
    st.caption("ESG vs Financial Performance — Indian Listed Firms (SEBI BRSR | Nifty 100)")

    tab1, tab2, tab3 = st.tabs(["🔍 Firm Explorer", "📈 ESG vs Returns", "🏆 Rankings"])

    # --- TAB 1: FIRM EXPLORER ---
    with tab1:
        selected_firm_name = st.selectbox("Select a firm to explore:", df['name'].tolist())
        firm_data = df[df['name'] == selected_firm_name].iloc[0]

        st.subheader(f"{firm_data['name']} ({firm_data['sector']})")

        # Financial & ESG Metrics
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Total ESG", firm_data['esg'])
        m2.metric("ROE (%)", firm_data['roe'])
        m3.metric("ROA (%)", firm_data['roa'])
        m4.metric("P/E Ratio", firm_data['pe'])

        # Pillar Chart
        pillar_df = pd.DataFrame({
            "Pillar": ["Environmental", "Social", "Governance"],
            "Score": [firm_data['e'], firm_data['s'], firm_data['g']]
        })
        fig_pillar = px.bar(pillar_df, x="Pillar", y="Score", color="Pillar",
                            color_discrete_sequence=["#1D9E75", "#378ADD", "#7F77DD"],
                            range_y=[0, 100], title=f"ESG Pillar Breakdown - {firm_data['name']}")
        st.plotly_chart(fig_pillar, use_container_width=True)

    # --- TAB 2: CORRELATION ---
    with tab2:
        st.subheader("ESG Score vs ROE")
        st.caption("Pearson r ≈ 0.38 | ESG vs ROA: r ≈ 0.52")

        fig_scatter = px.scatter(df, x="esg", y="roe", color="sector", hover_name="name",
                                 labels={"esg": "ESG Score", "roe": "ROE %"},
                                 size_max=10, size=[10]*len(df))
        st.plotly_chart(fig_scatter, use_container_width=True)

        st.subheader("Average ESG by Sector")
        sector_avg = df.groupby('sector')['esg'].mean().reset_index().sort_values(by='esg', ascending=False)
        fig_sector = px.bar(sector_avg, x="sector", y="esg", color="sector")
        st.plotly_chart(fig_sector, use_container_width=True)

    # --- TAB 3: RANKINGS ---
    with tab3:
        st.subheader("Leaderboard")
        st.dataframe(df.sort_values(by="esg", ascending=False).reset_index(drop=True),
                     use_container_width=True, hide_index=True)

# ==========================================
# 4. Chatbot UI (Right Column)
# ==========================================
with col2:
    st.title("💬 ESG Analyst Bot")

    # Initialize Chat History
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {"role": "assistant", "content": "Hi! I'm your ESG Analyst for Indian markets. I have ESG scores and financial data (ROE, ROA, P/E) for 15 Nifty-listed firms. Try asking about sector ESG patterns, firm comparisons, or ESG-financial correlations for your dissertation."}
        ]

    # Display Chat History
    chat_container = st.container(height=500)
    with chat_container:
        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])

    # Chat Input Box
    if prompt := st.chat_input("Ask about ESG scores, correlations, sectors..."):
        # Display user msg
        st.session_state.messages.append({"role": "user", "content": prompt})
        with chat_container:
            with st.chat_message("user"):
                st.markdown(prompt)

            # Generate and Display Assistant response
            with st.chat_message("assistant"):
                if model:
                    with st.spinner("Analyzing..."):
                        # Combine system prompt with history for context
                        full_prompt = SYSTEM_PROMPT + "\n\nChat History:\n"
                        for m in st.session_state.messages:
                            full_prompt += f"{m['role'].capitalize()}: {m['content']}\n"

                        try:
                            response = model.generate_content(full_prompt)
                            st.markdown(response.text)
                            st.session_state.messages.append({"role": "assistant", "content": response.text})
                        except Exception as e:
                            st.error(f"Error generating response: {e}")
                else:
                    msg = "⚠️ **API Key Missing**: Please set your Gemini API key in the script to enable the AI."
                    st.markdown(msg)
                    st.session_state.messages.append({"role": "assistant", "content": msg})

