# -*- coding: utf-8 -*-
"""rohhbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAy2WUmpxDYjgaiiPWT1b91iee2RHyzW
"""

pip install extra-streamlit-components

import streamlit as st
import pandas as pd
import plotly.express as px
import google.generativeai as genai
import yfinance as yf
import extra_streamlit_components as stx
import datetime
import uuid

# ==========================================
# 1. Page Configuration & Setup
# ==========================================
st.set_page_config(page_title="Live Corporate & ESG Finance Bot", layout="wide", page_icon="📈")

# ==========================================
# 2. User Tracking (Cookies)
# ==========================================
# Initialize the cookie manager
cookie_manager = stx.CookieManager()

# Try to get the existing user_id from their browser cookies
user_id = cookie_manager.get(cookie="user_id")

# If they don't have a cookie, create one
if user_id is None:
    user_id = f"user_{str(uuid.uuid4())[:8]}" # Creates a short unique ID like 'user_a1b2c3d4'
    # Set the cookie to expire in 30 days
    expire_date = datetime.datetime.now() + datetime.timedelta(days=30)
    cookie_manager.set("user_id", user_id, expires_at=expire_date)

# Log the user to your terminal so YOU know who is using it
print(f"Active Session: {user_id}")

# ==========================================
# 3. Sidebar: User Credentials & Setup
# ==========================================
with st.sidebar:
    st.header("🔑 AI Configuration")
    st.markdown("Use your own Google Gemini API key to power the chat.")

    # Show the tracking ID to the user (Optional: you can remove this if you want it completely hidden)
    st.caption(f"👤 Session ID: `{user_id}`")

    # User inputs their own API key
    user_api_key = st.text_input("Gemini API Key", type="password", placeholder="AIzaSy...")

    # User selects the model
    selected_model = st.selectbox(
        "Select AI Model",
        ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"]
    )

    st.divider()
    st.header("🔎 Asset Search")
    st.markdown("Enter a Yahoo Finance Ticker (e.g., **RELIANCE.NS** for NSE, **TCS.BO** for BSE, **AAPL** for US).")

    # Top Nifty tickers as a helper
    popular_tickers = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS", "ITC.NS"]
    selected_ticker = st.selectbox("Quick Select", ["Custom..."] + popular_tickers)

    if selected_ticker == "Custom...":
        target_ticker = st.text_input("Enter Custom Ticker", "RELIANCE.NS").upper()
    else:
        target_ticker = selected_ticker

# Configure AI if key is provided
model = None
if user_api_key:
    try:
        genai.configure(api_key=user_api_key)
        model = genai.GenerativeModel(selected_model)
    except Exception as e:
        st.sidebar.error(f"Error configuring API: {e}")
else:
    st.sidebar.warning("⚠️ Please enter an API key to enable the Chatbot.")

# ==========================================
# 4. Live Data Fetching Logic
# ==========================================
@st.cache_data(ttl=3600) # Cache data for 1 hour to prevent API limits
def fetch_company_data(ticker_symbol):
    try:
        tk = yf.Ticker(ticker_symbol)
        info = tk.info

        # Extract Financials
        financials = {
            "Name": info.get("longName", ticker_symbol),
            "Sector": info.get("sector", "N/A"),
            "Industry": info.get("industry", "N/A"),
            "ROE (%)": round(info.get("returnOnEquity", 0) * 100, 2) if info.get("returnOnEquity") else "N/A",
            "ROA (%)": round(info.get("returnOnAssets", 0) * 100, 2) if info.get("returnOnAssets") else "N/A",
            "P/E Ratio": round(info.get("trailingPE", 0), 2) if info.get("trailingPE") else "N/A",
            "Market Cap": info.get("marketCap", "N/A")
        }

        # Extract Governance/Officers
        officers_raw = info.get("companyOfficers", [])
        officers_list = []
        for officer in officers_raw:
            officers_list.append({
                "Name": officer.get("name", "Unknown"),
                "Age": officer.get("age", "N/A"),
                "Title": officer.get("title", "N/A"),
                "Exercised Value": officer.get("exercisedValue", 0)
            })
        df_officers = pd.DataFrame(officers_list) if officers_list else pd.DataFrame()

        return financials, df_officers
    except Exception as e:
        return None, None

# ==========================================
# 5. Main Dashboard UI
# ==========================================
col1, col2 = st.columns([1.5, 1], gap="large")

with col1:
    st.title("📊 Live Corporate Dashboard")

    with st.spinner(f"Fetching live data for {target_ticker}..."):
        fin_data, df_officers = fetch_company_data(target_ticker)

    if fin_data:
        st.subheader(f"{fin_data['Name']} ({target_ticker})")
        st.caption(f"Sector: {fin_data['Sector']} | Industry: {fin_data['Industry']}")

        # Financial Metrics
        m1, m2, m3 = st.columns(3)
        m1.metric("ROE (%)", fin_data['ROE (%)'])
        m2.metric("ROA (%)", fin_data['ROA (%)'])
        m3.metric("P/E Ratio", fin_data['P/E Ratio'])

        st.divider()

        # Governance Data
        st.subheader("👥 Corporate Governance: Board & Executives")
        st.caption("Data sourced live from Yahoo Finance.")
        if not df_officers.empty:
            st.dataframe(df_officers, use_container_width=True, hide_index=True)

            # Simple visualization of ages if available
            df_ages = df_officers[df_officers['Age'] != "N/A"].copy()
            if not df_ages.empty:
                df_ages['Age'] = pd.to_numeric(df_ages['Age'])
                fig = px.bar(df_ages, x="Name", y="Age", color="Title", title="Executive Ages")
                st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("No detailed officer data available for this ticker on Yahoo Finance.")
    else:
        st.error(f"Could not fetch data for {target_ticker}. Please check the ticker symbol.")

# ==========================================
# 6. Chatbot UI & Logic
# ==========================================
with col2:
    st.title("💬 Financial & ESG Analyst Bot")

    # Tie chat history to the specific user's session
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {"role": "assistant", "content": "Hi! I am your AI Financial Analyst. I can analyze the live data you pulled on the left, discuss corporate governance, or explain financial metrics. How can I help you today?"}
        ]

    chat_container = st.container(height=500)
    with chat_container:
        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])

    if prompt := st.chat_input("Ask about the company, governance, or financial health..."):

        # Log what specific users are asking in your backend terminal
        print(f"User [{user_id}] asked: {prompt}")

        st.session_state.messages.append({"role": "user", "content": prompt})
        with chat_container:
            with st.chat_message("user"):
                st.markdown(prompt)

            with st.chat_message("assistant"):
                if model:
                    with st.spinner("Analyzing..."):
                        # Build context from the live data
                        data_context = f"Company: {fin_data}\n\nGovernance Data:\n{df_officers.to_string() if df_officers is not None else 'N/A'}"

                        SYSTEM_PROMPT = f"""
                        You are an expert AI financial and corporate governance analyst.
                        The user is currently viewing the following live data for a specific stock:
                        {data_context}

                        Be concise, data-driven, and insightful. Base your analysis on the provided live data.
                        If the user asks about board demographics (age, roles), analyze the Governance Data provided.
                        """

                        full_prompt = SYSTEM_PROMPT + "\n\nChat History:\n"
                        for m in st.session_state.messages:
                            full_prompt += f"{m['role'].capitalize()}: {m['content']}\n"

                        try:
                            response = model.generate_content(full_prompt)
                            st.markdown(response.text)
                            st.session_state.messages.append({"role": "assistant", "content": response.text})
                        except Exception as e:
                            st.error(f"Error generating response: {e}. Please check your API key quota and validity.")
                else:
                    st.error("Please enter a valid Gemini API Key in the sidebar first.")

